collections:
  # Install a collection from Ansible Galaxy.
  - name: community.aws
    version: "7.2.0"
    source: https://galaxy.ansible.com
  - name: amazon.aws
    version: "7.6.1"
    source: https://galaxy.ansible.com
