---
- name: Install AWS CLI
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install AWS CLI using pip
      pip:
        name: awscli
        state: latest

    - name: Verify AWS CLI installation
      command: aws --version
      register: aws_version

    - debug:
        var: aws_version.stdout
