---
- name: Install AWS CLI
  hosts: localhost
    vars:
    ansible_connection: community.aws.aws_ssm
    ansible_aws_ssm_bucket_name: ansible-git-ssm-deployments
    ansible_aws_ssm_region: eu-south-1
  become: yes
  tasks:
    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install AWS CLI using pip
      pip:
        name: awscli
        state: latest

    - name: Verify AWS CLI installation
      command: aws --version
      register: aws_version

    - debug:
        var: aws_version.stdout
