---
- hosts: all
  #  become: true
  vars:
    ansible_connection: community.aws.aws_ssm
    ansible_aws_ssm_bucket_name: ansible-git-ssm-deployments
    ansible_aws_ssm_region: eu-south-1
      #  ansible_connection: 'community.aws.aws_ssm'
  tasks:
    - name: print disk space
      ansible.builtin.shell: df -hT
      register: out
    - name: Echo Disk space
      shell:
        cmd: "echo {{ out.stdout_lines }}"
      register: result
    - name: Show result
      debug:
       var: result
    #- debug: var=out.stdout_lines
        # Run the playbook
#ansible-playbook -i ./development_aws_ec2.yaml ./playbook.yaml
