---
- name: Wait for connection to be available
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: ansible-git-ssm-deployments
    ansible_aws_ssm_region: eu-south-1
    # When the S3 bucket isn't in the same region as the Instance
    # Explicitly setting the addressing style to 'virtual' may be necessary
    # https://repost.aws/knowledge-center/s3-http-307-response
    ansible_aws_ssm_s3_addressing_style: virtual
  tasks:
    - name: Wait for connection
      wait_for_connection:
      
- name: Update RedHat-based systems
  hosts: redhat
  become: true
  gather_facts: false

  tasks:

  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
  
- name: Update Debian-based systems
  hosts: ubuntu
  become: true
  gather_facts: false

  tasks:

  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
  
- name: Update Debian-based systems
  hosts: all
  become: true
  gather_facts: false

  tasks:

  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
